config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  post 'send_email', :to => :send_email, :controller => 'static_pages'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def send_email
    begin
      UserMailer.send_test_email(email_params).deliver_now
      redirect_to root_path, :notice => 'Email sent!'
    rescue
      redirect_to root_path, :alert => 'There was an error in sending the email.'
    end
  end

  private

    def email_params
      params.require(:email).permit(:from, :to, :subject, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Send Email Test
    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body
    .container
      - if notice
        .alert.alert-success.mt-3 role='alert'
          = notice
          button.close aria-label='close' data-dismiss='alert'
            span aria-hidden='true' &times;
      - if alert
        .alert.alert-danger.mt-3 role='alert'
          = alert
          button.close aria-label='close' data-dismiss='alert'
            span aria-hidden='true' &times;            
      = yield

app/views/static_pages/index.html.slim
.card.mt-3
  .card-body
    h4.card-title Send Test Email
    h6.card-subtitle.text-muted.mb-5 Form to send test email using AWS SES
    = form_tag send_email_path, :method => 'post'
      .form-group.row
        = label_tag 'From', 'From', :class => 'col-form-label col-md-2'
        .col-md-10
          = text_field_tag 'email[from]', ENV['FROM_EMAIL'], :class => 'form-control', :readonly => 'readonly'
      .form-group.row
        = label_tag 'To', 'To', :class => 'col-form-label col-md-2'
        .col-md-10
          = text_field_tag 'email[to]', nil, :class => 'form-control'
      .form-group.row
        = label_tag 'Subject', 'Subject', :class => 'col-form-label col-md-2'
        .col-md-10
          = text_field_tag 'email[subject]', nil, :class => 'form-control'
      .form-group.row
        = label_tag 'Message', 'Paste HTML', :class => 'col-form-label col-md-2'
        .col-md-10
          = text_area_tag 'email[message]', nil, :class => 'form-control'    
      .form-group.row
        .col-md-12
          = submit_tag 'Send Email', :class => 'btn btn-primary'